server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true